### ISSUE TITLE
KeyError: 'val-prior-noise-scale-log-size'

### ISSUE THREAD

**Issue by maabuu** [rssrwn/semla-flow#2]
I would like to predict a set of new molecules using the provided models from the [shared drive folder](https://drive.google.com/drive/folders/1rHi5JzN05bsGRGQUcWRmDu-Ilfoa9EAT).

The command `python -m semlaflow.predict --data_path=data/qm9/smol --ckpt_path models/qm9/300epochs.ckpt --dataset qm9 --n_molecules 100 --integration_steps 100 --save_dir predictions/qm9/100steps_100mols` returns an error:

```
Running prediction script for 100 molecules...
Using model stored at models/geom-drugs/200epochs.ckpt
Seed set to 12345
Current limits (soft, hard): (131072, 131072)
Open file limit already sufficiently large.
Building model vocab...
Vocab complete.
Loading datamodule...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/nagagpu04/not-backed-up/semla-flow/semlaflow/predict.py", line 243, in <module>
    main(args)
  File "/data/nagagpu04/not-backed-up/semla-flow/semlaflow/predict.py", line 199, in main
    dm = dm_from_ckpt(args, vocab)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/nagagpu04/not-backed-up/semla-flow/semlaflow/predict.py", line 154, in dm_from_ckpt
    dm = build_dm(args, hparams, vocab)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/nagagpu04/not-backed-up/semla-flow/semlaflow/predict.py", line 124, in build_dm
    scale_log_size=hparams["val-prior-noise-scale-log-size"],
                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'val-prior-noise-scale-log-size'
```

**Comment by rssrwn** [comment]
Ah sorry, I just forgot to update the prediction script with the most recent names for hyperparameters. Should be fixed on main now :)
